name: Validate and Test
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Test fixtures (simple)
        uses: ./
        with:
            path-to-workflows: '.github/workflows/fixtures/*.yml'
            show-ascii-art: false
      - name: Test all (advanced)
        uses: ./
        with:
          path-to-workflows: |-
            .github/**/*.yml
          show-ascii-art: true
